#!/bin/sh

#mount -a

mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug

source /etc/profile
sh /mountshare.sh

setlevel 8
echo "test echo"
sh /etc/network/config_tap
/etc/init.d/sshd start

